### ISSUE TITLE
Garrison units if not enough spaces available

### ISSUE THREAD

**Issue by Schwaggot** [RevoArma3/3den-Enhanced#24]
The old garrison tool had the feature that units that would not fit into buildings would still be put into garrison mode, so that you could just drag them into the right place and everything was fine. With the new tool this is not possible anymore. Could you please make the new tool behave like the old one in this case?

**Comment by RevoArma3** [comment]
I am not sure that I fully understand the issue. All units stay selected after all building positions are filled. Would you like to only have the left over units selected?

**Comment by Schwaggot** [comment]
Scenario: You have a building with 4 slots and a group of 6 men.

Old tool: Click garrison, 4 guys are garrisoned, message appears "not enough space for all of them"; Result: 4 guys are in the building in garrison and 2 left outside, but also in garrison mode (not walking away), then as a mission builder you can move them manually into place where you want them.

New tool: Not possible to garrison at all, since not enough space available, it displays message "Not enough empty building positions"; Desired Result: Same behavior as above, inside the given radius all possible places should be filled (4 guys) and the other 2 should not be moved, but put into garrison mode as well.

Also maybe an "Apply" button or something would be nice, it is strange to just selecting something and then closing using the X or Esc key.

**Comment by RevoArma3** [comment]
> but also in garrison mode (not walking away) What do you mean by that? There is no real garrison mode. The behaviour of the AI isn't changed at all.

> Also maybe an "Apply" button or something would be nice, it is strange to just selecting something and then closing using the X or Esc key.

Thanks, I'll see what I can do.
