### ISSUE TITLE
Functions Viewer is incompatible with Extended Functions Viewer

### ISSUE THREAD

**Issue by RevoArma3** [RevoArma3/3den-Enhanced#39]
https://forums.bohemia.net/forums/topic/222286-extended-function-viewer/?do=findComment&comment=3357281

**Comment by RevoArma3** [comment]
Fixed that by creating a small button in the top right corner.

**Comment by Freddo3000** [comment]
So I've run into this issue, and I'm wondering what small button you're talking about, as I can't seem to find it.

**Comment by R3voA3** [comment]
This changed didn't make it in to the released version yet.
